/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.model.Board;
import org.example.model.MeasuringTape;
import org.example.model.Segment;
import org.example.model.Model;
import org.example.model.Position;
import java.util.List;
import org.example.model.datasheet.DataSheet;
import org.example.model.datasheet.Movement;
import org.example.model.datasheet.Picture;
import org.example.model.datasheet.Stats;
import org.example.model.datasheet.Toughness;
import org.example.view.BoardView;
import org.example.view.PictureView;
import org.example.view.Scale;

import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Accordion;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.SplitPane;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Background;
import javafx.scene.layout.Border;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.Pane;
import javafx.scene.layout.Region;
import javafx.scene.layout.StackPane;
import javafx.scene.control.TitledPane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.shape.Line;
import javafx.scene.shape.Rectangle;
import javafx.scene.text.Text;
import javafx.stage.Stage;


public class App extends Application {
    
    
    private Parent createContent(){
        BorderPane root = new BorderPane();

        //tab pane
        VBox vbox = new VBox();

        Button button = new Button("hey");
        button.setOnMouseClicked(event2->{
            System.out.println("button clicke");
        });

        vbox.getChildren().addAll(button);
        root.setTop(vbox);
        
        //splitpane
        //left panel
        VBox leftpanel = new VBox();

        leftpanel.setMinWidth(50);
        leftpanel.setBackground(Background.fill(Color.LIGHTCYAN));


        //right sidePanel
        VBox rightpanel = new VBox();
        rightpanel.setMinWidth(200);
        rightpanel.setBackground(Background.fill(Color.LIGHTCYAN));

        

        Picture picture = new Picture("/custodian_guard.jpg");
        Stats stats = new Stats(
            new Movement(6),
            new Toughness(7)
        );
        DataSheet dataSheet = new DataSheet(picture,stats);

        PictureView pictureView = new PictureView(
                picture,
                rightpanel,
                new ImageView(new Image(getClass().getResourceAsStream(picture.getImagePath())))
        );

        GridPane gridPane = new GridPane();
        gridPane.setHgap(10);

        gridPane.add(new Label("M"), 0, 0);
        gridPane.add(new Label("T"), 1, 0);

        //stats
        gridPane.add(new Label("6"), 0, 1);
        gridPane.add(new Label("7"), 1, 1);

        gridPane.prefWidthProperty().bind(rightpanel.widthProperty());

        Accordion accordion = new Accordion();

        TitledPane pane1 = new TitledPane("Meele", new VBox());

        accordion.getPanes().addAll(pane1);
        rightpanel.getChildren().addAll(pictureView.getImageView(),gridPane,accordion);


        //board pane
        SplitPane splitPane = new SplitPane(leftpanel,this.makeBoardPane(),rightpanel);
        root.setCenter(splitPane);

        
        return root;
    }

    private Pane makeBoardPane(){
        Model model1 = new Model(1.5, 1.5, new Position(0, 0), new MeasuringTape(new Segment()));
        Model model2 = new Model(1.5, 1.5, new Position(5, 5), new MeasuringTape(new Segment()));
        Board board = new Board(44, 37, List.of(model1, model2));


        StackPane pane = new StackPane();
        pane.setBackground(Background.fill(Color.LIGHTGREEN));
        pane.setMinWidth(1000);

        //boardview
        Scale scale = new Scale(20);
        BoardView boardView = new BoardView(board,scale);

        pane.getChildren().addAll(boardView.getPane());

        return pane;
    }


    @Override
    public void start(Stage stage) {
        Scene scene = new Scene(this.createContent(), 640, 480);
        stage.setMaximized(true);
        stage.setScene(scene);
        stage.show();
    }
    	
    public static void main(String[] args) {
        launch(args);
    }
}
