/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.shape.Line;
import javafx.scene.shape.Rectangle;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import org.example.Mini;

public class App extends Application {

    private Pane createMini(){
        Rectangle model = new Rectangle(100, 50, Color.BLUE);
        Line measureTape = new Line(0, 0, 0, 0);
        Text text = new Text("1.0in");
        Pane pane = new Pane(model,measureTape,text);

        Mini mini = new Mini(model, measureTape, pane,text);

        return mini.getPane();
    }

    
    private Parent createContent(){
        VBox vbox = new VBox();
        

        Button button = new Button("hey");
        button.setOnMouseClicked(event2->{
            System.out.println("button clicke");
        });
        
        
        vbox.getChildren().addAll(button,this.createMini());
        return new Pane(vbox);
    }


    @Override
    public void start(Stage stage) {
        Scene scene = new Scene(this.createContent(), 640, 480);
        stage.setMaximized(true);
        stage.setScene(scene);
        stage.show();
    }
    	
    public static void main(String[] args) {
        launch(args);
    }
}
