/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.shape.Line;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;


public class App extends Application {
    private Pane createMini(){
        Pane pane = new Pane();
        Rectangle model = new Rectangle(100, 50, Color.BLUE);
        Line measureTape = new Line(0, 0, 0, 0);

        model.setOnMousePressed(event -> {
            model.setUserData(new double[]{
                model.getTranslateX() - event.getSceneX(),
                model.getTranslateY() - event.getSceneY()
            });
            double centerX = model.getTranslateX()+model.getWidth()/2;
            double centerY = model.getTranslateY()+model.getHeight()/2;
            measureTape.setStartX(centerX);
            measureTape.setStartY(centerY);
            measureTape.setEndX(centerX);
            measureTape.setEndY(centerY);
        });

        model.setOnMouseDragged(event -> {
            double[] offset = (double[]) model.getUserData();
            model.setTranslateX(event.getSceneX() + offset[0]);
            model.setTranslateY(event.getSceneY() + offset[1]);
            measureTape.setEndX(model.getTranslateX()+model.getWidth()/2);
            measureTape.setEndY(model.getTranslateY() + model.getHeight() / 2);
        });

        pane.getChildren().addAll(model, measureTape);

        return pane;
    }

    
    private Parent createContent(){
        VBox vbox = new VBox();
        

        Button button = new Button("hey");
        button.setOnMouseClicked(event2->{
            System.out.println("button clicke");
        });
        
       
        
        vbox.getChildren().addAll(button,this.createMini());
        return new Pane(vbox);
    }


    @Override
    public void start(Stage stage) {
        Scene scene = new Scene(this.createContent(), 640, 480);
        stage.setMaximized(true);
        stage.setScene(scene);
        stage.show();
    }
    	
    public static void main(String[] args) {
        launch(args);
    }
}
